### PR TITLE
Update Viewer API version.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/pull/59.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Complexity increasing per file
==============================
- src/AppDomainGenerator/DomainGenerator.cs  2
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298867&bid=17344234)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
- src/AppDomainGenerator/DomainGenerator.cs  2
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298866&bid=17344233)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
- src/AppDomainGenerator/DomainGenerator.cs  2
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298866&bid=17344233)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/AppDomainGenerator/DomainGenerator.cs  2
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298866&bid=17344233)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298866&bid=17344233)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           

Complexity increasing per file
==============================
- src/Products/Viewer/Config/ViewerConfiguration.cs  1
- src/Products/Common/Util/Comparator/FileDateComparator.cs  2
- src/Products/Viewer/Cache/ConcurrentDictionaryKeyLockerStore.cs  1
- src/Products/Viewer/Cache/ThreadSafeCache.cs  1
- src/Products/Viewer/Controllers/ViewerApiController.cs  1
- src/AppDomainGenerator/DomainGenerator.cs  2
         

Clones removed
==============
+ src/Products/Viewer/Controllers/ViewerApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/pullRequest?prid=5298867&bid=17344234)

**Pull request merged**
